[tools]
node = "lts"
bun = "latest"
"claude-code" = "latest"
gemini = "latest"
lazygit = "latest"
glow = "latest"
usage = "latest"
pnpm = "latest"
# go = "latest"
# python = "latest"
# uv = 'latest'
# lazydocker = "latest"
"npm:nb.sh" = "latest"

[hooks]
enter = "mise install"

[settings]
experimental = true
idiomatic_version_file_enable_tools = ["node"]
