[tools]
node = "lts"
bun = "latest"                 # package manager
go = "latest"
usage = "latest"
"npm:opencode-ai" = "latest"   # ai coding agent
"npm:agent-browser" = "latest" # browser automation cli
lazygit = "latest"                       # git tui
glow = "latest"                          # markdown preview - used by nb
"go:golang.org/x/tools/gopls" = "latest"
"go:github.com/hmans/beans" = "latest"

[hooks]
enter = "mise install"

[settings]
experimental = true
idiomatic_version_file_enable_tools = ["node"]
